name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  test:
    env:
      COURIER_WS_URL: ${{ secrets.COURIER_WS_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "12.x"
          scope: "@trycourier"
          always-auth: true
      - run: yarn
      - run: yarn lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: yarn build:components
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "courier-components-xvdza5"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "./packages/components/dist"
